### ISSUE TITLE
order by id

### ISSUE THREAD

**Issue by huynguyen93** [cleverage/eav-api-platform-bundle#1]
I want to do a GET request `/api/resources?order[id]=DESC` to sort results by id
My configurations:
```yml
services:
    api.filter.order:
        parent: CleverAge\EAVApiPlatformBundle\Filter\OrderFilter
        tags:
            - { name: api_platform.filter, id: api.filter.order }

resources:
    App\Entity\Resource:
        attributes:
            filters:
                - api.filter.order
```
But I got 500 error with message: `No attribute with code : Unknown attribute id in family Resource`.

**Comment by VincentChalnot** [comment]
The id is a standard Doctrine attribute, you juste have to follow the API Platform documentation on this one:
https://api-platform.com/docs/core/filters/

**Comment by huynguyen93** [comment]
ok, I got it working now with `api_platform.doctrine.orm.order_filter`, thank you very much @VincentChalnot

**Comment by huynguyen93** [comment]
Sorry, but I have another problem:
Let's say my `Resource` now has an attribute `title`, and I want to offer order filter for both `id` and `title`, my api resource config:
```
resources:
    App\Entity\Resource:
        attributes:
            filters:
                - api.filter.order # this is to sort by `title`
                - api.filter.api-platform.order # this is to sort by `id`
```
Not sure if this is the correct config? If I sort by `id`, `api.filter.order` will process first and thow an error `Unknown attribute id`.

I made some tests and `api_platform.doctrine.orm.order_filter` ignores if attribute not exist. I guess we should do the same?

**Comment by VincentChalnot** [comment]
You're right! There is a bug indeed, there is no check against the property of the order by in the OrderFilter logic.
Do you think you can provide a PR to fix this ?
The idea is to use the already existing logic inside the AbstractEAVFilter to update the OrderFilter so that it only applies for declared properties like other filters.

**Comment by huynguyen93** [comment]
I have just tried it again and could not reproduce yesterday's problem, I must have done something wrong yesterday.
I check `AbstractEAVFilter` and it's working with this [line](https://github.com/cleverage/eav-api-platform-bundle/blob/01ffc8d6c176cef50fb6374d637a3860cecfa6f7/Filter/AbstractEAVFilter.php#L157) being called before OrderFilter::filterAttribute

for reference, it's working with this config:
```
resources:
    App\EavEntity\Resource:
        attributes:
            filters:
                - api.filter.order
                - api.filter.api-platform.order

services:
    api.filter.order:
        parent: CleverAge\EAVApiPlatformBundle\Filter\OrderFilter
        arguments:
              - {title: ~}
        tags:
            - { name: api_platform.filter, id: api.filter.order }

    api.filter.api-platform.order:
        parent: api_platform.doctrine.orm.order_filter
        arguments:
            - {id: ~}
        tags:
            - { name: api_platform.filter, id: api.filter.api-platform.order }
```
